//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quicksilver.Business.ProductRegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdRegItem", Namespace="http://schemas.datacontract.org/2004/07/Quicksilver.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class ProdRegItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductRegistrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegisteredDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductRegistrationId {
            get {
                return this.ProductRegistrationIdField;
            }
            set {
                if ((this.ProductRegistrationIdField.Equals(value) != true)) {
                    this.ProductRegistrationIdField = value;
                    this.RaisePropertyChanged("ProductRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((this.RegisteredDateField.Equals(value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductRegistrationService.IProductRegistrationService")]
    public interface IProductRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRegistrationService/GetAllProductRegistrations", ReplyAction="http://tempuri.org/IProductRegistrationService/GetAllProductRegistrationsResponse" +
            "")]
        Quicksilver.Business.ProductRegistrationService.ProdRegItem[] GetAllProductRegistrations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRegistrationService/GetAllProductRegistrations", ReplyAction="http://tempuri.org/IProductRegistrationService/GetAllProductRegistrationsResponse" +
            "")]
        System.Threading.Tasks.Task<Quicksilver.Business.ProductRegistrationService.ProdRegItem[]> GetAllProductRegistrationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRegistrationService/GetProductRegistration", ReplyAction="http://tempuri.org/IProductRegistrationService/GetProductRegistrationResponse")]
        Quicksilver.Business.ProductRegistrationService.ProdRegItem GetProductRegistration(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductRegistrationService/GetProductRegistration", ReplyAction="http://tempuri.org/IProductRegistrationService/GetProductRegistrationResponse")]
        System.Threading.Tasks.Task<Quicksilver.Business.ProductRegistrationService.ProdRegItem> GetProductRegistrationAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductRegistrationServiceChannel : Quicksilver.Business.ProductRegistrationService.IProductRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductRegistrationServiceClient : System.ServiceModel.ClientBase<Quicksilver.Business.ProductRegistrationService.IProductRegistrationService>, Quicksilver.Business.ProductRegistrationService.IProductRegistrationService {
        
        public ProductRegistrationServiceClient() {
        }
        
        public ProductRegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Quicksilver.Business.ProductRegistrationService.ProdRegItem[] GetAllProductRegistrations() {
            return base.Channel.GetAllProductRegistrations();
        }
        
        public System.Threading.Tasks.Task<Quicksilver.Business.ProductRegistrationService.ProdRegItem[]> GetAllProductRegistrationsAsync() {
            return base.Channel.GetAllProductRegistrationsAsync();
        }
        
        public Quicksilver.Business.ProductRegistrationService.ProdRegItem GetProductRegistration(int id) {
            return base.Channel.GetProductRegistration(id);
        }
        
        public System.Threading.Tasks.Task<Quicksilver.Business.ProductRegistrationService.ProdRegItem> GetProductRegistrationAsync(int id) {
            return base.Channel.GetProductRegistrationAsync(id);
        }
    }
}
